#include <YSI_Coding\y_hooks>

//------------------------- Definitions and constants -------------------------
#define FOLDER_ANTICHEAT_MONEY          "ServerLogs/AntiCheat/money_hack.log"
#define FOLDER_ANTICHEAT_ADVERTISING    "ServerLogs/AntiCheat/advertising_hack.log"
#define FOLDER_ADMIN_PAR 		        "ServerLogs/Admins/par_log.log"

//------------------------- Data (This section is for module-internal data. Make sure to make the accessor variable 'static') -------------------------

//------------------------- External API (Functions accessible from other modules. Use 'stock' and PascalCase.) -------------------------

//------------------------- Internal API (Functions to be used only inside of this module. Use 'static (stock)' and camelCase) -------------------------

//------------------------- Implementation (This section contains the concrete implementation for this module inside of the callbacks) -------------------------
