#include <YSI_Coding\y_hooks>

//------------------------- Definitions and constants -------------------------
#define		COLOR_YELLOW     0xFFFF00AA
#define		COLOR_YELLOW2	 0xb18904FF
#define   	COLOR_INVALID    0xB4B5B7FF
#define		COLOR_SOFTBLUE	 0x127be4FF
#define		COLOR_SOFTBLUE2  0x0080ffFF
#define   	COLOR_DARKBLUE	 0x2641FEC8
#define   	COLOR_LIGHTBLUE  0x33CCFFAA
#define   	COLOR_SKIN       0xffcc99FF
#define   	COLOR_ADMIN      0xff3399FF
#define   	COLOR_DBLUE      0x2641feFF
#define   	COLOR_WHITE      0xFFFFFFAA
#define   	COLOR_GRAD1      0xB4B5B7FF
#define   	COLOR_GRAD2      0xBFC0C2FF
#define   	COLOR_GRAD3      0xCBCCCEFF
#define   	COLOR_GRAD4      0xD8D8D8FF
#define   	COLOR_GRAD5      0xE3E3E3FF
#define   	COLOR_GRAD6      0xF0F0F0FF
#define     COLOR_GREY       0xAFAFAFAA
#define		COLOR_SOFTGREY	 0x848484FF
#define     COLOR_NEONGREEN  0x33ff00FF
#define     COLOR_LIGHTGREEN 0x9acd32FF
#define   	COLOR_FADE1      0xE6E6E6E6
#define   	COLOR_FADE2      0xC8C8C8C8
#define   	COLOR_FADE3      0xAAAAAAAA
#define   	COLOR_FADE4      0x8C8C8C8C
#define   	COLOR_FADE5      0x6E6E6E6E
#define		COLOR_SERVICE	 0x6666ccFF
#define		COLOR_MARKET	 0x934ff6FF
#define   	COLOR_PURPLE     0x9900ffFF
#define   	COLOR_LIGHTPU    0xC2A2DAAA
#define   	COLOR_LIGHTRED   0xff6347FF
#define		COLOR_PINK		 0xf04b87ff
#define   	COLOR_NEONPINK   0xFF1493FF
#define   	COLOR_DARKGREEN  0x33AA33AA
#define   	COLOR_3DLABEL    0xF68E00F6
#define   	COLOR_RED     	 0xaa3333FF
#define     COLOR_LRED       0xFF0000FF
#define     COLOR_GREEN      0x00FF00FF
#define		COLORDGREEN		 0x228b22FF
#define     COLOR_BLUE       0x005FFFFF
#define     COLOR_FROSTBLUE  0x8d8dffFF
#define     COLOR_LIGHTPINK  0xe960a4FF
#define   	COLOR_DEPARTMENT 0x993333FF
#define   	COLOR_CHATGANG   0x90EE90FF
#define   	COLOR_VIP        0xFFCCFFAA
#define   	COLOR_SOCIO      0xa86db4FF
#define     COLOR_TITLE      0xffff00FF
#define		COLOR_ORANGE	 0xf68e00FF
#define     COLOR_ORANGE2    0xFFA500FF
#define     COLOR_NEWS       0xFFA500AA
#define   	COLOR_BABYBLUE   0xCCCCFFFF
#define   	COLOR_RADIO      0x6666CCFF
#define		COLOR_NCHAT		 0x009999FF
#define     COLOR_CYAN       0x00e7c6FF

//------------------------- Data (This section is for module-internal data. Make sure to make the accessor variable 'static') -------------------------

//------------------------- Timers (Timers used in the module.) -------------------------

//------------------------- Internal API (Functions to be used only inside of this module. Use 'static (stock)' and camelCase) -------------------------

//------------------------- External API (Functions accessible from other modules. Use 'stock' and PascalCase.) -------------------------

//------------------------- Implementation (This section contains the concrete implementation for this module inside of the callbacks) -------------------------

//------------------------- Commands (Module related commands) -------------------------
