#include <map_spawn>
#include <map_house_login>
#include <map_city_hall>
#include <map_city_hall_square>
#include <map_gas_station>
#include <map_gas_station_verona>
#include <map_driving_school>
#include <map_court_of_justice>

#include <YSI_Coding\y_hooks>

//------------------------- Definitions and constants -------------------------

//------------------------- Data (This section is for module-internal data. Make sure to make the accessor variable 'static') -------------------------

//------------------------- External API (Functions accessible from other modules. Use 'stock' and PascalCase.) -------------------------

//------------------------- Internal API (Functions to be used only inside of this module. Use 'static (stock)' and camelCase) -------------------------

//------------------------- Implementation (This section contains the concrete implementation for this module inside of the callbacks) -------------------------
